Biome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(),name="Home"),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^Groups/",include("Groups.urls", namespace="Groups")),
]

Groups/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'Groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from Groups import views as second

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single1"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

Groups/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.text import slugify

# Create your models here.
import mistune

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        renderer = mistune.Renderer(escape=True, hard_wrap=True)
        # use this renderer instance
        markdown = mistune.Markdown(renderer=renderer)
        self.description_html = markdown(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        print(self.slug)
        return reverse("Groups:single", kwargs={"slug":self.slug})

    class Meta:
        ordering = ["name"]

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships",on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

Groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(LoginRequiredMixin,PermissionRequiredMixin)
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from Groups.models import Group,GroupMember
from . import models

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("Groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("Groups:single",kwargs={"slug": self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

Groups/templates/Groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

Groups/templates/Groups/group_detail.html
{% extends "Groups/group_base.html" %}

{% block pregroup %}

<div class="container">
	<h5>{{group.name}} (Member Count: {{group.members.count}})<span>
		{% if user in group.members.all %}
			<a href="{% url 'Groups:leave' slug=group.slug %}" class="btn btn-outline-primary"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
		{% else %}
			<a href="{% url 'Groups:join' slug=group.slug %}" class="btn btn-outline-primary"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
		{% endif %}
	</span>
	</h5>
</div>


{% endblock %}


{% block group_content %}

<div class="col-md-12">
	{% if group.posts.count == 0 %}
	<h2>No posts in this group yet!</h2>

	{% else %}

		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	{% endif %}
</div>
{% endblock %}

Groups/templates/Groups/group_form.html
{% extends "Groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}

<div class="container">
<h4>Create A New BIOME Group</h4>
</div>

<div class="container">
  <form method="POST" action="{% url 'Groups:create' %}" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create" class="btn btn-outline-primary">
  </form>
</div>

{% endblock %}

Groups/templates/Groups/group_list.html
{% extends "Groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-5">
	<div class="content">
		{% if user.is_authenticated %}
		<h1>Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h1>

		{% else %}
		<h1> BIOME Communities!! </h1>

    {% endif %}
			<p align="justify">You’re building a community. We’re here to help. Select a Group with a shared interest!</p>
			<p align="justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>

	{% if user.is_authenticated %}
	<a href="{% url 'Groups:create' %}" class="btn btn-outline-primary"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-7">
	<div class="list-group">
		{% for group in object_list %}
		  <a class="list-group-item" href="{% url 'Groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> member{{group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		<hr />
		{% endfor %}
	</div>
</div>
{% endblock %}