Biome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(),name="Home"),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^Groups/",include("Groups.urls", namespace="Groups")),
]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from Groups import views as second

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single1"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
  <meta charset="utf-8">
  <title>Biome</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Optional theme -->

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <!-- Custom Fonts for the Website -->
  <link href="https://fonts.googleapis.com/css?family=Anton|Montserrat" rel="stylesheet">
  <link href="//db.onlinewebfonts.com/c/d0374bf16da70eff39d6f085935f8882?family=DTLProkyonST" rel="stylesheet" type="text/css"/>



  <!-- Link to the local CSS stylesheet -->
  <link rel="stylesheet" href="{% static 'Biome/css/master.css'%}">

</head>

<body data-spy="scroll" >

  <div class="container">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand nav-left" href="{% url "Home" %}" id="brand">BIOME</a>
        <ul class="navbar navbar-dark bg-primary">
          {% if user.is_authenticated %}
          <li><a href="{% url 'posts:create' %}" class="btn btn-outline-primary" id="navigateitems">Post a Message</a></li>
          <li><a href="{% url 'Groups:all' %}" class="btn btn-outline-primary" id="navigateitems">BIOME Groups</a></li>
          <li><a href="{% url 'Groups:create' %}" class="btn btn-outline-primary" id="navigateitems" >Create a New Community</a></li>
          <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple" id="navigateitems">Log out</a></li>
          {% else %}
          <li><a href="{% url 'Groups:all' %}" class="btn btn-outline-primary" id="navigateitems">BIOME Groups</a></li>
          <li><a href="{% url 'accounts:login' %}" class="btn btn-outline-primary" id="navigateitems">Log in</a></li>
          <li><a href="{% url 'accounts:signup' %}" class="btn btn-outline-primary" id="navigateitems">Sign up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>

  <div class="jumbotron">
    {% block content %}

    {% endblock %}
  </div>
</body>

<!-- Link to the JavaScript styling sheet -->
<script src="{% static 'Biome/js/master.js'%}"></script>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>Welcome to BIOME!!!</h1>
  <table>
  <tr>
    <td align="justify" valign="top" >
      <p>A forum for building a new generation of sustainability innovators through active networking and idea sharing.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p><span><a href="{% url "accounts:login" %}"><button type="button" class="btn btn-outline-primary">Login</button></span></a>
      <span><a href="{% url "accounts:signup" %}"><button type="button" class="btn btn-outline-primary">Sign-up Today -- Its Free!!!</button></span></a></p>
    </td>
    <td align="center" valign="center" >
    <img src="https://www.industryweek.com/sites/industryweek.com/files/styles/article_featured_standard/public/uploads/2014/12/1-gecko.jpg?itok=89nf8ML3" style="width:500px;height:300px;" alt="random image" />
  </td>
  </tr>

  </table>

</div>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'Groups:all'%}">Go to Groups</a></h2>
</div>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <h1>Thanks for visiting! Come back soon!</h1>
</div>

{% endblock %}